# Generated by Django 2.2.2 on 2019-08-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ssid',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='file',
            name='student_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
