# Generated by Django 2.2.2 on 2019-08-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knnapp', '0002_auto_20190803_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ssid',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
